### ISSUE TITLE
Need to change DISP_SIZE

### ISSUE THREAD

**Issue by ggvili** [siposcsaba89/stereo-sgm-opencl#4]
Hi,

I need to change DISP_SIZE from 128 to 64, but i was not able to do it. Can anyone please help with that?

Thanks,
Gabi

**Comment by siposcsaba89** [comment]
Hi Gabi,

If you want to change the DISP_SIZE to 64, you need to rewrite some kernels (matching_cost_kernel_128, stereo_loop_128, winner_takes_all_kernel128) and maybe also need to change some kernel launch parameters, like thread num and block num.  

If you are familiar what the kernels doing its like copy paste.

If I would have time, I would do it. Please contact me if you have any further questions.

Regards,
Csaba

ps.:  Bocs, de nem vagyunk mi honfi társak, magyaros neved van? :)

**Comment by ggvili** [comment]
Hi Csaba,

Thanks for your respond.
I am not Hungarian, i could read what you have wrote in Hungarian thanks to google translate. My name Gabi is a short of Gabriel which is a very common name in the world.

Yesterday after many trials and errors i succeeded in getting the disparity with DISP_SIZE of 64 done correctly.
I understand what all the CL kernels are doing beside what the scan_cost (aggregation) kernels compute_stereo....._dir_kernel_X are doing.
I tried to write semi global disparity in open CL directly from C source code but the aggregation kernels took too much time, because i couldn't avoid from having a for-loop on full row or column and another nested for-loop on the disparities what was very restrictive for the open CL thus caused a very bad run time results.
In your aggregation kernels it seems that you have only for-loop on a full row or column but there is no for-loop on the disparities, if you can explain how it is done it would very helpful for me.

Thanks for your help.
Gabi

**Comment by siposcsaba89** [comment]
Hi Gabi,

Sorry for the late answer, but I was very busy and was in Japan for 2 weeks.
You cannot see the for loop on the disparities, because it is running parallel over the disparities and perpendicular to the given path and iterates only over the path direction, because it cannot be parallelized  due to the recurrent nature of the algorithm. You can check this paper for detailed description of the parallel implementation of sgm:
https://arxiv.org/pdf/1610.04121.pdf

Sorry again.
Best regards,
Csaba

**Comment by jasonlinuxzhang** [comment]
https://github.com/jasonlinuxzhang/sgbm_cuda   
After my test, it is 3-4 times faster than the cpu version of the opencv sgbm algorithm, and the effect is exactly the same as opencv sgbm. The maximum disparity can be set to an integer multiple of 32, the maximum is 256.
